TARGET = iphone:latest:5.0
ARCHS = armv6 armv7 armv7s arm64
GO_EASY_ON_ME = 1

include theos/makefiles/common.mk
TWEAK_NAME = EmoShortcut
EmoShortcut_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
