SDKVERSION = 8.0
ARCHS = armv7 armv7s arm64
GO_EASY_ON_ME = 1

include theos/makefiles/common.mk
TWEAK_NAME = QuickEmo
QuickEmo_FILES = Tweak.xm
QuickEmo_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
